services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/database
    depends_on:
      - db
    networks:
      - red-china

  db:
    container_name: db
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - red-china
    ports:
      - "5432:5432"
    expose:
      - 5432 

  frontend:
    container_name: frontend
    build:
      context: ./FrontEnd/ArrozChino-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    networks:
      - red-china

volumes:
  pgdata:

networks:
  red-china:
    external: true